import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import "@/app/styles/index.css"
import {APIOptions, PrimeReactProvider } from 'primereact/api';
import 'primeicons/primeicons.css';
import Layout from "./layout_custom";
import { GlobalProvider } from "./components/Context";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const primeReactValue: Partial<APIOptions> = {
  ripple: true,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider value={primeReactValue}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProvider>

        <Layout>
                    {children}
        </Layout>
        </GlobalProvider>
      </body>
      </PrimeReactProvider>
    </html>
  );
}
